CREATE TABLE `ums_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `member_level_id` BIGINT(20) DEFAULT NULL,
  `username` VARCHAR(64) DEFAULT NULL COMMENT '用户名',
  `password` VARCHAR(64) DEFAULT NULL COMMENT '密码',
  `nickname` VARCHAR(64) DEFAULT NULL COMMENT '昵称',
  `phone` VARCHAR(64) DEFAULT NULL COMMENT '手机号码',
  `status` INT(1) DEFAULT NULL COMMENT '帐号启用状态:0->禁用；1->启用',
  `create_time` DATETIME DEFAULT NULL COMMENT '注册时间',
  `icon` VARCHAR(500) DEFAULT NULL COMMENT '头像',
  `gender` INT(1) DEFAULT NULL COMMENT '性别：0->未知；1->男；2->女',
  `birthday` DATE DEFAULT NULL COMMENT '生日',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '所做城市',
  `job` VARCHAR(100) DEFAULT NULL COMMENT '职业',
  `personalized_signature` VARCHAR(200) DEFAULT NULL COMMENT '个性签名',
  `source_type` INT(1) DEFAULT NULL COMMENT '用户来源',
  `integration` INT(11) DEFAULT NULL COMMENT '积分',
  `growth` INT(11) DEFAULT NULL COMMENT '成长值',
  `luckey_count` INT(11) DEFAULT NULL COMMENT '剩余抽奖次数',
  `history_integration` INT(11) DEFAULT NULL COMMENT '历史积分数量',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  UNIQUE KEY `idx_phone` (`phone`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='用户表'

CREATE TABLE `pms_product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `brand_id` BIGINT(20) DEFAULT NULL,
  `product_category_id` BIGINT(20) DEFAULT NULL,
  `feight_template_id` BIGINT(20) DEFAULT NULL,
  `product_attribute_category_id` BIGINT(20) DEFAULT NULL,
  `name` VARCHAR(64) NOT NULL,
  `pic` VARCHAR(255) DEFAULT NULL,
  `product_sn` VARCHAR(64) NOT NULL COMMENT '货号',
  `delete_status` INT(1) DEFAULT NULL COMMENT '删除状态：0->未删除；1->已删除',
  `publish_status` INT(1) DEFAULT NULL COMMENT '上架状态：0->下架；1->上架',
  `new_status` INT(1) DEFAULT NULL COMMENT '新品状态:0->不是新品；1->新品',
  `recommand_status` INT(1) DEFAULT NULL COMMENT '推荐状态；0->不推荐；1->推荐',
  `verify_status` INT(1) DEFAULT NULL COMMENT '审核状态：0->未审核；1->审核通过',
  `sort` INT(11) DEFAULT NULL COMMENT '排序',
  `sale` INT(11) DEFAULT NULL COMMENT '销量',
  `price` DECIMAL(10,2) DEFAULT NULL,
  `promotion_price` DECIMAL(10,2) DEFAULT NULL COMMENT '促销价格',
  `gift_growth` INT(11) DEFAULT '0' COMMENT '赠送的成长值',
  `gift_point` INT(11) DEFAULT '0' COMMENT '赠送的积分',
  `use_point_limit` INT(11) DEFAULT NULL COMMENT '限制使用的积分数',
  `sub_title` VARCHAR(255) DEFAULT NULL COMMENT '副标题',
  `description` TEXT COMMENT '商品描述',
  `original_price` DECIMAL(10,2) DEFAULT NULL COMMENT '市场价',
  `stock` INT(11) DEFAULT NULL COMMENT '库存',
  `low_stock` INT(11) DEFAULT NULL COMMENT '库存预警值',
  `unit` VARCHAR(16) DEFAULT NULL COMMENT '单位',
  `weight` DECIMAL(10,2) DEFAULT NULL COMMENT '商品重量，默认为克',
  `preview_status` INT(1) DEFAULT NULL COMMENT '是否为预告商品：0->不是；1->是',
  `service_ids` VARCHAR(64) DEFAULT NULL COMMENT '以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮',
  `keywords` VARCHAR(255) DEFAULT NULL,
  `note` VARCHAR(255) DEFAULT NULL,
  `album_pics` VARCHAR(255) DEFAULT NULL COMMENT '画册图片，连产品图片限制为5张，以逗号分割',
  `detail_title` VARCHAR(255) DEFAULT NULL,
  `detail_desc` TEXT,
  `detail_html` TEXT COMMENT '产品详情网页内容',
  `detail_mobile_html` TEXT COMMENT '移动端网页详情',
  `promotion_start_time` DATETIME DEFAULT NULL COMMENT '促销开始时间',
  `promotion_end_time` DATETIME DEFAULT NULL COMMENT '促销结束时间',
  `promotion_per_limit` INT(11) DEFAULT NULL COMMENT '活动限购数量',
  `promotion_type` INT(1) DEFAULT NULL COMMENT '促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购',
  `brand_name` VARCHAR(255) DEFAULT NULL COMMENT '品牌名称',
  `product_category_name` VARCHAR(255) DEFAULT NULL COMMENT '商品分类名称',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='商品信息'

CREATE TABLE `oms_order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `member_id` BIGINT(20) NOT NULL,
  `coupon_id` BIGINT(20) DEFAULT NULL,
  `order_sn` VARCHAR(64) DEFAULT NULL COMMENT '订单编号',
  `create_time` DATETIME DEFAULT NULL COMMENT '提交时间',
  `member_username` VARCHAR(64) DEFAULT NULL COMMENT '用户帐号',
  `total_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '订单总金额',
  `pay_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '应付金额（实际支付金额）',
  `freight_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '运费金额',
  `promotion_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '促销优化金额（促销价、满减、阶梯价）',
  `integration_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '积分抵扣金额',
  `coupon_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '优惠券抵扣金额',
  `discount_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '管理员后台调整订单使用的折扣金额',
  `pay_type` INT(1) DEFAULT NULL COMMENT '支付方式：0->未支付；1->支付宝；2->微信',
  `source_type` INT(1) DEFAULT NULL COMMENT '订单来源：0->PC订单；1->app订单',
  `status` INT(1) DEFAULT NULL COMMENT '订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单',
  `order_type` INT(1) DEFAULT NULL COMMENT '订单类型：0->正常订单；1->秒杀订单',
  `delivery_company` VARCHAR(64) DEFAULT NULL COMMENT '物流公司(配送方式)',
  `delivery_sn` VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
  `auto_confirm_day` INT(11) DEFAULT NULL COMMENT '自动确认时间（天）',
  `integration` INT(11) DEFAULT NULL COMMENT '可以获得的积分',
  `growth` INT(11) DEFAULT NULL COMMENT '可以活动的成长值',
  `promotion_info` VARCHAR(100) DEFAULT NULL COMMENT '活动信息',
  `bill_type` INT(1) DEFAULT NULL COMMENT '发票类型：0->不开发票；1->电子发票；2->纸质发票',
  `bill_header` VARCHAR(200) DEFAULT NULL COMMENT '发票抬头',
  `bill_content` VARCHAR(200) DEFAULT NULL COMMENT '发票内容',
  `bill_receiver_phone` VARCHAR(32) DEFAULT NULL COMMENT '收票人电话',
  `bill_receiver_email` VARCHAR(64) DEFAULT NULL COMMENT '收票人邮箱',
  `receiver_name` VARCHAR(100) NOT NULL COMMENT '收货人姓名',
  `receiver_phone` VARCHAR(32) NOT NULL COMMENT '收货人电话',
  `receiver_post_code` VARCHAR(32) DEFAULT NULL COMMENT '收货人邮编',
  `receiver_province` VARCHAR(32) DEFAULT NULL COMMENT '省份/直辖市',
  `receiver_city` VARCHAR(32) DEFAULT NULL COMMENT '城市',
  `receiver_region` VARCHAR(32) DEFAULT NULL COMMENT '区',
  `receiver_detail_address` VARCHAR(200) DEFAULT NULL COMMENT '详细地址',
  `note` VARCHAR(500) DEFAULT NULL COMMENT '订单备注',
  `confirm_status` INT(1) DEFAULT NULL COMMENT '确认收货状态：0->未确认；1->已确认',
  `delete_status` INT(1) NOT NULL DEFAULT '0' COMMENT '删除状态：0->未删除；1->已删除',
  `use_integration` INT(11) DEFAULT NULL COMMENT '下单时使用的积分',
  `payment_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receive_time` DATETIME DEFAULT NULL COMMENT '确认收货时间',
  `comment_time` DATETIME DEFAULT NULL COMMENT '评价时间',
  `modify_time` DATETIME DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='订单表'

CREATE TABLE `oms_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) DEFAULT NULL COMMENT '订单id',
  `order_sn` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `product_id` bigint(20) DEFAULT NULL,
  `product_pic` varchar(500) DEFAULT NULL,
  `product_name` varchar(200) DEFAULT NULL,
  `product_brand` varchar(200) DEFAULT NULL,
  `product_sn` varchar(64) DEFAULT NULL,
  `product_price` decimal(10,2) DEFAULT NULL COMMENT '销售价格',
  `product_quantity` int(11) DEFAULT NULL COMMENT '购买数量',
  `product_sku_id` bigint(20) DEFAULT NULL COMMENT '商品sku编号',
  `product_sku_code` varchar(50) DEFAULT NULL COMMENT '商品sku条码',
  `product_category_id` bigint(20) DEFAULT NULL COMMENT '商品分类id',
  `promotion_name` varchar(200) DEFAULT NULL COMMENT '商品促销名称',
  `promotion_amount` decimal(10,2) DEFAULT NULL COMMENT '商品促销分解金额',
  `coupon_amount` decimal(10,2) DEFAULT NULL COMMENT '优惠券优惠分解金额',
  `integration_amount` decimal(10,2) DEFAULT NULL COMMENT '积分优惠分解金额',
  `real_amount` decimal(10,2) DEFAULT NULL COMMENT '该商品经过优惠后的分解金额',
  `gift_integration` int(11) DEFAULT '0',
  `gift_growth` int(11) DEFAULT '0',
  `product_attr` varchar(500) DEFAULT NULL COMMENT '商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单中所包含的商品'

