spring:
  shardingsphere:
    datasource:
      names: ds1,ds3
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:13306/kimmking?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds3:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:13307/kimmking?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        order:
          actual-data-nodes: ds1.sys_user$->{1..16}, ds3.sys_user$->{1..16}
          key-generator:
            column: user_id
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds$->{user_id%2==0?1:3}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: sys_user$->{user_id%16+1}
    props:
      sql.show: true



